<?php
CREATE DATABASE mydatabase;

USE mydatabase;

CREATE TABLE users (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL,
    email VARCHAR(50),
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE passkeys (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    passkey VARCHAR(30) NOT NULL,
    expiry_date DATE NOT NULL
);

CREATE TABLE purchase (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT(6) NOT NULL,
    product_name VARCHAR(30) NOT NULL,
    quantity INT(6) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
?>
